// src/components/KinkCategory.svelte
<script lang="ts">
import { createEventDispatcher } from 'svelte';
export let cat: { name: string; fields: string[]; kinks: string[] };
export let selection: Record<string, number> = {};
const dispatch = createEventDispatcher();

const levels = [
  { label: 'Not Entered', class: 'notEntered' },
  { label: 'Favorite', class: 'favorite' },
  { label: 'Like', class: 'like' },
  { label: 'Okay', class: 'okay' },
  { label: 'Maybe', class: 'maybe' },
  { label: 'No', class: 'no' }
];

function getKey(cat: string, field: string, kink: string) {
  return `${cat}|${field}|${kink}`;
}

function selectLevel(cat: string, field: string, kink: string, level: number) {
  dispatch('select', {cat, field, kink, level});
}
</script>
<div class="kinkCategory cat-{cat.name.replace(/\s+/g, '').toLowerCase()}">
  <h2>{cat.name}</h2>
  <table class="kinkGroup">
    <thead>
      <tr>
        {#each cat.fields as field}
          <th class="choicesCol">{field}</th>
        {/each}
        <th>Kink</th>
      </tr>
    </thead>
    <tbody>
      {#each cat.kinks as kink}
        <tr class="kinkRow kink-{kink.replace(/\s+/g, '').toLowerCase()}">
          {#each cat.fields as field}
            <td>
              <div class="choices">
                {#each levels as l, i}
                  <button
                    class="choice {l.class} {selection[getKey(cat.name, field, kink)] === i ? 'selected' : ''}"
                    title={l.label}
                    on:click={() => selectLevel(cat.name, field, kink, i)}
                  ></button>
                {/each}
              </div>
            </td>
          {/each}
          <td>{kink}</td>
        </tr>
      {/each}
    </tbody>
  </table>
</div>

// neo-kinklist/src/components/KinkCategory.tsx
import React from 'react';
import KinkRow from './KinkRow';
import { strToClass } from '../utils';

interface KinkCategoryProps {
  name: string;
  fields: string[];
  kinks: string[];
}

const KinkCategory: React.FC<KinkCategoryProps> = ({ name, fields, kinks }) => {
  return (
    <div className={`kinkCategory cat-${strToClass(name)}`} data-category={name}>
      <h2>{name}</h2>
      <table className="kinkGroup" data-fields={fields.join(',')}>
        <thead>
          <tr>
            {fields.map(field => (
              <th key={field} className="choicesCol">{field}</th>
            ))}
            <th></th>
          </tr>
        </thead>
        <tbody>
          {kinks.map(kink => (
            <KinkRow 
              key={kink} 
              categoryName={name} 
              kinkName={kink} 
              fields={fields} 
            />
          ))}
        </tbody>
      </table>
    </div>
  );
};

export default KinkCategory;
