// src/components/Legend.tsx
import React from 'react'
import { useTranslation } from 'react-i18next'
import { useKinklist } from '../context/KinklistContext'

const Legend: React.FC = () => {
  const { levels } = useKinklist()
  const { t } = useTranslation()

  // Mapping von Level-Namen zu i18n-Schlüsseln
  const getLevelTranslationKey = (levelName: string): string => {
    const keyMap: Record<string, string> = {
      'Not Entered': 'legend.notEntered',
      Favorite: 'legend.favorite',
      Like: 'legend.like',
      Okay: 'legend.okay',
      Maybe: 'legend.maybe',
      No: 'legend.no',
    }

    return (
      keyMap[levelName] ||
      `legend.${levelName.toLowerCase().replace(/\s+/g, '')}`
    )
  }

  return (
    <div className="legend-container">
      <div className="legend">
        <h2 className="legend-title">{t('legend.title')}</h2>
        {Object.entries(levels).map(([levelKey, level]) => (
          <div className="legend-item" key={levelKey}>
            <span
              data-color={level.color}
              className={`choice ${level.class}`}
            />
            <span className="legend-text">{t(`legend.${level.key}`)}</span>
          </div>
        ))}
      </div>
    </div>
  )
}

export default Legend

// src/components/Legend.svelte
<script lang="ts">
const levels = [
  { label: 'Not Entered', color: '#FFFFFF', class: 'notEntered' },
  { label: 'Favorite', color: '#6DB5FE', class: 'favorite' },
  { label: 'Like', color: '#23FD22', class: 'like' },
  { label: 'Okay', color: '#FDFD6B', class: 'okay' },
  { label: 'Maybe', color: '#DB6C00', class: 'maybe' },
  { label: 'No', color: '#920000', class: 'no' }
];
</script>
<div class="legend">
  {#each levels as l}
    <div>
      <span class="choice {l.class}" style="background-color: {l.color}"></span>
      <span class="legend-text">{l.label}</span>
    </div>
  {/each}
</div>
